### ISSUE TITLE
Amazon autofill not working 

### ISSUE THREAD

**Issue by TheCodesterr** [LEDfan/keywi#118] opened 2018-09-02 14:24 UTC
It is a two step page where you enter your username is first and then your password on the next page fyi.

**Comment by RobinJadoul** [comment] 2018-09-02 14:41
Can you provide the url?

**Comment by TheCodesterr** [comment] 2018-09-02 14:43
https://www.amazon.com/ap/signin?openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_ya_signin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=usflex&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&&openid.pape.max_auth_age=0

**Comment by RobinJadoul** [comment] 2018-09-02 15:10
Can you provide detailed steps or a screencast? It seems to work for me. (Did you use `Fill password` for the second step?)

**Comment by TheCodesterr** [comment] 2018-09-02 15:14
I've tried both filling just the username and username and pass. It used to work, but I don't know if Amazon updated their site.

![screen shot 2018-09-02 at 11 12 26 am](https://user-images.githubusercontent.com/34100586/44957516-5bec9880-aea1-11e8-87c9-a330680384f4.png)
![screen shot 2018-09-02 at 11 12 36 am](https://user-images.githubusercontent.com/34100586/44957518-5bec9880-aea1-11e8-85a1-88dabc204b12.png)

**Comment by RobinJadoul** [comment] 2018-09-02 15:27
It doesn't even fill a username? I assumed the problem was with the second step not filling the password. You may need to fill the password separately, due to the separated nature of the login page.

**Comment by TheCodesterr** [comment] 2018-09-02 15:28
Yeah it doesn't fill the username either. Youtube works fine and it's the same type of autofill screens.

**Comment by RobinJadoul** [comment] 2018-09-02 15:36
cc @LEDfan 
After testing, it seems the context menu is not properly triggering any action. Using the hotkeys seems to work however. This does mean that I can reproduce the problem.
@TheCodesterr Can you confirm that filling the username works with the hotkey (`ctrl + F`)

**Comment by TheCodesterr** [comment] 2018-09-02 15:37
@RobinJadoul I'm on a Mac, so I'm unable to use that feature.

**Comment by RobinJadoul** [comment] 2018-09-02 15:38
That should no longer be a problem since #94, using ctrl instead of cmd

**Comment by TheCodesterr** [comment] 2018-09-02 15:40
I saw that fix, but for some reason that is still not working for me.

**Comment by RobinJadoul** [comment] 2018-09-02 15:40
Correction: the hotkey is <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>F</kbd>

**Comment by RobinJadoul** [comment] 2018-09-02 15:41
Hmmm, I'm unable to test on mac, but I thought we had some kind of test at that time to confirm the fixed worked...

**Comment by TheCodesterr** [comment] 2018-09-02 15:41
Right, I tried that and I'm not sure why it's not working for me

**Comment by TheCodesterr** [comment] 2018-09-02 15:43
Just tried it on a website that is working with the manual auto fill option and confirmed it's still not working.

**Comment by RobinJadoul** [comment] 2018-09-02 15:45
Anyway, we'll see if the problem is indeed related to the context menu (which seems likely at this point), and try to investigate the mac hotkey issue when we have a chance

**Comment by TheCodesterr** [comment] 2018-09-02 15:48
Sounds good thank you!

**Comment by Riajyuu** [comment] 2018-09-02 15:48
I also encounter this from time to time. For me it's github and protomail

**Comment by RobinJadoul** [comment] 2018-09-03 00:36
I can reproduce on amazon, but not on github or protonmail
Further investigation could take a bit more time

**Comment by TheCodesterr** [comment] 2018-09-10 21:30
Update: I found that when I have Firefox already running, then open KeePass and enter my password to connect them, it will not autofill.

**Comment by LEDfan** [comment] 2018-09-11 05:43
@TheCodesterr do you have the "Don't unlock the Secure Storage on startup" option enabled? (You can check this on the about:addons page)

I tried to reproduce the issue with the following steps:
  
 1. close all firefox and keepass instances
 2. open firefox
 3. unlock the secure storage
 4. open and unlock keepass
 5. go to the amazon link
 6. try to fill in a credential (using shortcut or contextmenu) -> works

**Comment by TheCodesterr** [comment] 2018-09-11 07:34
No that option is not checked.

On Sep 11, 2018, at 1:43 AM, Tobia De Koninck <notifications@github.com<mailto:notifications@github.com>> wrote:


@TheCodesterr<https://github.com/TheCodesterr> do you have the "Don't unlock the Secure Storage on startup" option enabled? (You can check this on the about:addons page)

I tried to reproduce the issue with the following steps:

  1.  close all firefox and keepass instances
  2.  open firefox
  3.  unlock the secure storage
  4.  open and unlock keepass
  5.  go to the amazon link
  6.  try to fill in a credential (using shortcut or contextmenu) -> works

**Comment by TheCodesterr** [comment] 2018-09-12 00:58
I actually did have that option checked.

I just unchecked it, and did your steps, and it’s still not working. I used to work flawlessly. I don’t know what’s going on.

**Comment by LEDfan** [comment] 2021-03-13 15:10
Latest version(s) work fine on Amazon, therefore I'm closing this issue.

**Closed by LEDfan** 2021-03-13 15:10 UTC
